name: Deploy StoryScribe Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install backend deps
        run: |
          pip install -r backend/requirements.txt
          python - <<'PY'
import importlib; import sys
for m in ["fastapi","uvicorn","azure.cosmos"]:
    if not importlib.util.find_spec(m):
        print(f"Missing {m}")
        sys.exit(1)
print("Dependencies OK.")
PY

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: "20"

      - name: Frontend install
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Artifact (frontend)
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: frontend/dist

          